version: '3.8'

services:
  my-mongodb:
    image: mongo
    container_name: my-mongodb
    networks:
      - my-mongo-network
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}

networks:
  my-mongo-network:
    driver: bridge
